name: Idea Proposal
description: Suggest a new idea or feature for Happy Timesheet.
title: "[IDEA]: "
labels: ["enhancement", "idea"]
projects: ["users/philffm/projects/6"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a new idea for Happy Timesheet!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: idea-summary
    attributes:
      label: Idea Summary
      description: Provide a brief summary of the idea or feature you are proposing.
      placeholder: Briefly describe your idea.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this idea is important for improving the timesheet experience in Dynamics 365. What problem does it solve or what aspect does it enhance?
      placeholder: Why is this idea important?
    validations:
      required: true
  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the idea, including how it aligns with Happy Timesheet's goals of friendly language, motivational content, or dynamic UI enhancements.
      placeholder: Describe your idea in detail.
    validations:
      required: true
  - type: textarea
    id: potential-challenges
    attributes:
      label: Potential Challenges
      description: Discuss any potential challenges or considerations that might arise with this idea, especially in terms of user experience or technical implementation.
      placeholder: What challenges might this idea face?
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples that might help in understanding the idea. Consider how it could integrate with existing features like affirmations or animations.
      placeholder: Any additional context or examples?
